# Site settings
title: Definitely Real Kate's blog
header-img: img/home-bg.png
email: kate+travers@flatironschool.com
copyright_name: kttravers
description: > # this means to ignore newlines until "baseurl:"
  Very real.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kttravers
learn_profile: kttravers
email_username: kate+travers@flatironschool.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
